export {default as HeroSection} from "./HeroSection"
export {default as Navbar} from "./Navbar"
export {default as Problems} from "./KeyProblems.jsx"
export {default as KeyMetric} from "./KeyMetric.jsx"
export {default as Reviews} from "./Reviews.jsx"
export {default as Features} from "./Features.jsx"
export {default as CTAContainer} from "./Cta.jsx"
export {default as Footer} from "./Footer.jsx"